// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4QelVi5U98HRdlTKqfdSo_p0WFfa0o7U',
    appId: '1:424602228709:web:12ce9197a37d7146ed810c',
    messagingSenderId: '424602228709',
    projectId: 'conselec-7242d',
    authDomain: 'conselec-7242d.firebaseapp.com',
    storageBucket: 'conselec-7242d.appspot.com',
    measurementId: 'G-DDWJLV8FYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAesPzC1lZ4LCcycZMI67ddiWO_X3H01M',
    appId: '1:424602228709:android:7aa04221cca0b856ed810c',
    messagingSenderId: '424602228709',
    projectId: 'conselec-7242d',
    storageBucket: 'conselec-7242d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkFwfm-YOEX26_r79i6-NZTuvP4lZH_xU',
    appId: '1:424602228709:ios:5d4b28be68c09523ed810c',
    messagingSenderId: '424602228709',
    projectId: 'conselec-7242d',
    storageBucket: 'conselec-7242d.appspot.com',
    iosBundleId: 'com.example.conselec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkFwfm-YOEX26_r79i6-NZTuvP4lZH_xU',
    appId: '1:424602228709:ios:5d4b28be68c09523ed810c',
    messagingSenderId: '424602228709',
    projectId: 'conselec-7242d',
    storageBucket: 'conselec-7242d.appspot.com',
    iosBundleId: 'com.example.conselec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4QelVi5U98HRdlTKqfdSo_p0WFfa0o7U',
    appId: '1:424602228709:web:baea196e702b88efed810c',
    messagingSenderId: '424602228709',
    projectId: 'conselec-7242d',
    authDomain: 'conselec-7242d.firebaseapp.com',
    storageBucket: 'conselec-7242d.appspot.com',
    measurementId: 'G-7REVKTNZLT',
  );
}
